### ISSUE TITLE
Documentation: Uglykit Overview. 

### ISSUE THREAD

**Issue by wa8gl** [waggle-sensor/waggle#10]
-- Unboxing instructions. ( email list, set up guide)
-- Uglykit Manifest and Overview. 
-- Uglykit Getting Started (exist, add to it).

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #9](https://github.com/waggle-sensor/development/issues/9) via [**ZenHub**](https://www.zenhub.com/)
