### ISSUE TITLE
Deployment: Steps to Steamline for the Uglykits and further extend for AoT nodes. 

### ISSUE THREAD

**Issue by wa8gl** [waggle-sensor/waggle#12]
Samurai pre-ship To Do: 

Hardware prep: 
  -- Firmware for the Wagman (boot loader and firmware), and Airsense (firmware)
     (pull, modify, compile, flash)
 
Node Prep:
    -- Press four images : SD-C1P SD-XU4 eMMC-C1P eMMC-XU4 (GIT is already in it).
    -- Run Configure Script to set node ID, and create CName.
    -- Register UglyKit with User in Database.
    -- Create folder with Cert, nodes.txt (node IDs and other configurations).
    -- Run firmware install scripts
    -- Reboot & Check Beehive
         -- see data live 
         -- data.txt

**Comment by MuffinSpawn** [comment]
This issue is outdated. Closing...
