### ISSUE TITLE
SPI pin on Airsense board

### ISSUE THREAD

**Issue by seonghapark** [waggle-sensor/waggle#21]
To do SPI communication between airsense board and alpha sensor, it needs 6 pins to get command and send data. But the SPI pins marked on Airsense board  for SPI does not provide Slave Select/Chip Select pin (which is supposed to be pin 5, but it's master-reset).

So we need to use one of GPIO pins for SS/CS to do SPI communication for v3.2 airsense board. Now the coresense firmware v3.2 uses pin 33.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #12](https://github.com/waggle-sensor/development/issues/12) via [**ZenHub**](https://www.zenhub.com/)
