### ISSUE TITLE
SSH Host Public on Nodes

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/waggle#24]
I realized over the weekend that I don't think the nodes explicitly have the ssh host public key included in a secure way. It also seems that currently the nodes do not validate the host when connecting over ssh by using the "StrictHostKeyChecking no" flag.

This isn't hard to do but (I think) it's crucial to make this an explicit step of the deployment process ASAP. This will provide some confidence that the nodes are actually talking to beehive hosts...

*In the first paragraph, by securely, I mean, it's likely that in the Argonne network this transfer happens securely, but, we shouldn't take that for granted and have an explicit procedure for doing this.*

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #10](https://github.com/waggle-sensor/development/issues/10) via [**ZenHub**](https://www.zenhub.com/)
