### ISSUE TITLE
Remote Watchdog for Waggle Nodes

### ISSUE THREAD

**Issue by wa8gl** [waggle-sensor/waggle#3]
Currently, we have no way to know when a Waggle Node starts acting poorly, or is just plan dead.  The situation has causes us to loose data.  We need two things:

1) A piece of software that sits somewhere on the internet and checks for the data on Beehive.  If data is missing, it raises an alarm (SMS, email, etc)

2) A new, crude piece of software on beehive that does simple QA, and alerts via SMS, email if sensor values start going bad.

**Comment by geeklair** [comment]
We have to fix this in the next update... we can't tell when a node dies.

**Comment by MuffinSpawn** [comment]
Moving to the development repository...

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #13](https://github.com/waggle-sensor/development/issues/13) via [**ZenHub**](https://www.zenhub.com/)
