### ISSUE TITLE
Public Backlog / task management tool

### ISSUE THREAD

**Issue by MuffinSpawn** [waggle-sensor/waggle#30]
I'm experimenting with the ZenHub "integration" right now. It seems to do what we need.

**Comment by MuffinSpawn** [comment]
Need:
- bug/feature tracking
- Project Management
- Project snapshots (weekly)
- Filter on sprint

**Comment by MuffinSpawn** [comment]
I assigned this to those I think might be interested in using ZenHub. To get burndown graphs and the task board view you'll need to install the Chrome/Firefox browser plugin. Take a look and see what you think.

**Comment by wa8gl** [comment]
Ok.  At some point we will need a walk-through of how to use the features you are interested in.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #6](https://github.com/waggle-sensor/development/issues/6) via [**ZenHub**](https://www.zenhub.com/)
