### ISSUE TITLE
Beehive data pipeline initial functional version

### ISSUE THREAD

**Issue by MuffinSpawn** [waggle-sensor/waggle#32]

**Comment by wcatino** [comment]
Re-opened. @MuffinSpawn: If you wanted this closed for some reason, please close it again.

**Comment by MuffinSpawn** [comment]
Bill, I closed this because it was moved here: waggle-sensor/development#4. Sorry for the confusion.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #50](https://github.com/waggle-sensor/development/issues/50) via [**ZenHub**](https://www.zenhub.com/)
