### ISSUE TITLE
Need Golden Master Image for XU4

### ISSUE THREAD

**Issue by wa8gl** [waggle-sensor/waggle#4]
An image for the XU4 is needed

**Comment by wgerlach** [comment]
For the moment we will have two images for the XU4, each with different partition UUID's. Once we figure out how to recover from SD card to eMMC, we should be able to require only one image, similar to the C1+.

**Comment by MuffinSpawn** [comment]
What exactly is preventing recovery on the XU4?

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #8](https://github.com/waggle-sensor/development/issues/8) via [**ZenHub**](https://www.zenhub.com/)
