### ISSUE TITLE
Coresense Watchdog

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/waggle#48]
In the next bug fix for the coresense firmware, we should consider using the SAM's watchdog.  While going through the test process for the sensor pod, I had the coresense get into a mode where it stopped sending data over the serial port and just required a reset.

Since I use that in the Wagman firmware, I could also add that to the coresense when we have time. A little extra resilience never hurts... It's probably best practice anyway...

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #231](https://github.com/waggle-sensor/development/issues/231) via [**ZenHub**](https://www.zenhub.com/)
