### ISSUE TITLE
Coresense Framing Mod

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/waggle#49]
Since I'm writing about firmware enhancements for the coresense, let me add one more I've been thinking about for quite a long time...

I think a worthwhile enhancement to the coresense packet framing is to incorporate proper byte escaping. Most of you may already be familiar with this, but the basic idea is this:

You fix some special START, END, ESCAPE bytes. You send a START and END byte before / after every message like we’ve been doing already. The only change is, while sending the payload you do the following byte escaping:

```
send START

for byte in payload {
	if byte is START, END, or ESCAPE {
		send ESCAPE
		send byte ^ 0x20 // just a way to mask the special byte
	} else {
		send byte
	}
}

send END
```

That way, you’ve remove all special framing and escape bytes from the serial stream which makes catching a message much, *much* easier, since you never can encounter special bytes as part of the payload. Unescaping is also trivial.

Yes, you add an extra byte few bytes every now and then, but with reasonably chosen special bytes, you rarely have to escape anything, so the average increase in packet size is very low - probably only a byte or two. Plus, in the worst case it only doubles the packet size.

All of the additional "checks", like the length and CRC just get sent along with the payload and can be left unchanged.

I’d say for the tiny amount of effort this takes, it’s probably worth thinking about… :)

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #232](https://github.com/waggle-sensor/development/issues/232) via [**ZenHub**](https://www.zenhub.com/)
