### ISSUE TITLE
trouble with submodules

### ISSUE THREAD

**Issue by ericvh** [waggle-sensor/waggle#51]
I was trying to follow the instructions in the developer branch and some of the repos don't exit (or perhaps aren't public) -- in particular waggle-protocol

Any hint on what I'm doing wrong?

**Comment by rajeshxsankaran** [comment]
Hello. The documentation stitching the repos together is not up-to-date. We are in the process of cleaning up the repos and the documentation. In the meanwhile, the pywaggle module implements the waggle-protocol - 

https://github.com/waggle-sensor/pywaggle

The eWaggle module provides the same support for embedded devices like Arduinos and Particle devices. 

https://github.com/waggle-sensor/eWaggle

**Comment by ericvh** [comment]
okay, updating the issue - let me know when its fixed.  We want to try and reproduce build setup sooner rather than later.   Thanks.

**Comment by rajeshxsankaran** [comment]
We never fixed, we just made something new and cooler!
